### ISSUE TITLE
Headers installation directory

### ISSUE THREAD

**Issue by remicollet** [awesomized/libmemcached#100]
With version 1.1.0beta1, we have in /usr/include

```
ibmemcached
libmemcached-1
libmemcached-1.0 -> libmemcached-1
```

IMHO would make more sense to have 

```
libmemcached
libmemcached-1 -> libmemcached-1.0
libmemcached-1.0 
```

And in short, for packaging, replacing a dir with a symlink is a nightmare ;)

Or even dropped this "lilbmemcached-1" directory, I don't think it make sense, can stay at 1.0 as long as API is not broken

ex

- atk 2.36 use atk 1.0
- libbson 1.17 use libbson-1.0
- glib 2.66 use glib-2.0
- gtk 3.24 use gtk-3.0
- etc

**Comment by m6w6** [comment]
Makes sense, thank you. Reverted.

**Comment by remicollet** [comment]
Thanks :)
