### ISSUE TITLE
Do you have instructions for building in Windows Server 2019?

### ISSUE THREAD

**Issue by StasToken** [awesomized/libmemcached#109]
How to build it under Windows?

**Comment by m6w6** [comment]
Should just work for MSVC as well as MinGW, just ensure msys' bin is in your path; see the [CI workflow for Windows](https://github.com/m6w6/libmemcached/actions/runs/512279394/workflow#L353); f.e.:

```
cmake --config Release -S . -B build
cmake --build build --config Release
```

**Comment by StasToken** [comment]
@m6w6 - It's strange - I'm doing something completely wrong or I don't understand something... my cmake version 3.20.1
```
C:\memcache\libmemcached>cmake --config Release -S . -B build
CMake Error: Unknown argument --config
CMake Error: Run 'cmake --help' for all supported options.
```

I looked at help and there really is no such option

**Comment by m6w6** [comment]
Sigh. Looks like a regression in CMake 3.20 -- thanks for the report!

**Comment by m6w6** [comment]
Maybe try 

```
cmake -S . -B build
cmake --build build --config Release
```

for now...

**Comment by StasToken** [comment]
Thank you very much this recipe worked. @m6w6 I would suggest that you include it in the readme file - and then somehow it turns out that the Windows developers are deprived of the official instructions...

From myself I want to add that for the build you need to install: 

1. [Visual Studio](https://visualstudio.microsoft.com/)
2. [cmake](https://cmake.org/download/)
3. [bison_flex (site)](http://www.talkplayfun.com/) Direct link: [win_flex_bison.zip](http://www.talkplayfun.com/bison_flex/win_flex_bison.zip)
4. bison_flex After installation, it should be configured, [this instruction](https://youtu.be/PC4QztYgeWA) helped me
5. `cmake -S . -B build`
6. `cmake --build build --config Release`

_PS: Thank you very much for your help in solving the problem @m6w6_

**Comment by m6w6** [comment]
👍 Thank you very much. I'll look into improving the Readme!
