### ISSUE TITLE
Add static version of library

### ISSUE THREAD

**Issue by dakorn** [awesomized/libmemcached#132]

**Comment by m6w6** [comment]
Hey @dakorn! Would `cmake -DBUILD_SHARED_LIBS=OFF` as implemented in #133 work in your case?

**Comment by dakorn** [comment]
I have tried it, but it still produces only shared libraries. I think there is missing a configuration in cmake files for that.

**Comment by m6w6** [comment]
It's there, though. Did you reset your CMake cache?

**Comment by dakorn** [comment]
Maybe I am missing something.

I have just cloned this repository and run cmake:

`cmake -DBUILD_SHARED_LIBS=OFF ../libmemcached`

But I still have only:
`[ 15%] Linking CXX shared library libhashkit.so`
`[ 74%] Linking CXX shared library libmemcached.so`

**Comment by m6w6** [comment]
Did you checkout the `gh-132/static-libs` branch?

**Comment by m6w6** [comment]
Looks like the name `ALIAS`ing is broken, though. It just produces `liblibxyz.a`
